""".

Revision ID: 292ba11f4d5b
Revises: 759956745d6a
Create Date: 2021-05-05 07:46:21.845851

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '292ba11f4d5b'
down_revision = '759956745d6a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
