"""Product

Revision ID: 385dec45fd59
Revises: 8bdeb9a4c052
Create Date: 2021-05-05 07:37:42.091410

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '385dec45fd59'
down_revision = '8bdeb9a4c052'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
