""".

Revision ID: 759956745d6a
Revises: ba89edb375c9
Create Date: 2021-05-05 07:46:04.089855

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '759956745d6a'
down_revision = 'ba89edb375c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
