""".

Revision ID: a541d80796ee
Revises: 292ba11f4d5b
Create Date: 2021-05-05 07:46:27.943587

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a541d80796ee'
down_revision = '292ba11f4d5b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
