""".

Revision ID: ba89edb375c9
Revises: 385dec45fd59
Create Date: 2021-05-05 07:45:49.979076

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba89edb375c9'
down_revision = '385dec45fd59'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
